### ISSUE TITLE
Missing Readme

### ISSUE THREAD

**Issue by TechnologyClassroom** [lightningcpu/Notification-Alerter#1]
Even a brief description copied from F-Droid and a link would be better than nothing.

The app sounds interesting. I've been looking for something like this. Had trouble installing.

**Comment by lightningcpu** [comment]
Greetings! You're right. I'll add that briefly. Please let me know if it works. Make sure to enable any required permissions if you aren't prompted to do so.

**Comment by TechnologyClassroom** [comment]
I tried again with success. Third times a charm.

**Comment by lightningcpu** [comment]
What OS are you using? (For example MIUI, LineageOS, Sailfish OS).

**Comment by TechnologyClassroom** [comment]
Latest GrapheneOS (Android 14) with Neo Store (F-Droid alternative). Likely could have been related to Neo Store.
